apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  message: SGVsbG8gR3VydSE= #Encoded data need to pass in secret and we used base64 encoded
---
apiVersion: v1
kind: Pod
metadata:
  name: sc-demo-1
spec:
  containers:
    - name: debug
      image: rkalluru/debug
      env:
        - name: URL
          valueFrom:
            secretKeyRef:
              name: sc-demo           # The ConfigMap this value comes from.
              key: message # The key to fetch.
