apiVersion: v1
kind: Pod
metadata:
  name: {{ .values.podName }} # accessing variable in values.yml file
spec:
  containers:
    - name: nginx
      image: {{ .values.image }} # accessing image variable in values.yml file
      ports:
        - containerPort: 80