#  key-value store used to manage configuration data in Kubernetes
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
data:
  CATALOGUE_HOST: "catalogue-dev.azdevops2704.online"
  CATALOGUE_PORT: "8080" # In kubernetes nums should be ""
  REDIS_HOST: "redis-dev.azdevops2704.online"

---
# Deploy and manage your application in a containerized environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cart

---
# To expose a set of Pods to other services within the cluster or to external traffic, depending on its type
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
  app: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


