#  key-value store used to manage configuration data in Kubernetes
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: frontend
#data:
#  CATALOGUE_HOST: "catalogue"
#  CATALOGUE_PORT: "8080"
#  USER_HOST: "user"
#  USER_PORT: "8080"
#  CART_HOST: "cart"
#  CART_PORT: "8080"
#  SHIPPING_HOST: "shipping"
#  SHIPPING_PORT: "8080"
#  PAYMENT_HOST: "payment"
#  PAYMENT_PORT: "8080"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: frontend
  dataFrom:
    - extract:
        key: frontend
---
# Deploy and manage your application in a containerized environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: frontend

---
# To expose a set of Pods to other services within the cluster or to external traffic, depending on its type
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer # cloud will create a Ip address to expose the outside
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


