#  key-value store used to manage configuration data in Kubernetes
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb-dev.azdevops2704.online:27017/users"
  REDIS_URL: "redis://redis-dev.azdevops2704.online:6379"

---
# Deploy and manage your application in a containerized environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user
---
# To expose a set of Pods to other services within the cluster or to external traffic, depending on its type
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
  app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080